### ISSUE TITLE
¿Cómo mostrar las políticas de privacidad y el manual de usuario?

### ISSUE THREAD

**Issue by renatojobal** [willyborja95/Camello#107]
He visto que las mayoría de aplicaciones no descargan un pdf cuando uno desea ver las políticas de privacidad; que es lo que estamos haciendo actualmente en la aplicación. 

Pensaba que podría crear fragments para ello, pero luego me di cuenta que tendría que escribir muchísimo texto dentro de los recursos de texto, lo cuál no creo que sea buena idea.

**Comment by renatojobal** [comment]
Hola @JamesJose7 . Disculpa que te moleste nuevamente. Estaba dudando sobre como sobrellevar este issue. Recordé que en un live por Facebook que hicieron con @willyborja95 hablaste sobre algo para resolver este problema. Creo que mencionaste utilizar un gist pero no estoy seguro de ello. 

Espero me puedas ayudar. Muchas gracias de antemano.

**Comment by JamesJose7** [comment]
Hola @renatojobal, no te preocupes pregúntame cuando quieras. Github pages es la mejor opción en términos de facilidad y flexibilidad que he visto que usan y personalmente he usado, sobretodo cuando se tienen recursos limitados. Aquí están algunas de las ventajas que se me ocurren por el momento:

- Mantienes los cambios y el source code de la misma dentro del mismo repositorio. 
- El hosting de la página es gratis.
- Puedes escribirla completamente con markdown que simplifica la construcción y edición de la página.
- Una vez publicada puedes enlazarla en la aplicación con un link para abrirlo externamente, o tener una webview interna que abra la página y el contenido es completamente responsivo sin ningún esfuerzo adicional.
- Te sirve el link para referenciar las políticas en recursos externos como al desplegarla a la playstore, ya que ahí te piden que ingreses un link a una página donde estén tus políticas de forma pública. Así cumples dos objetivos con un solo esfuerzo.

**Comment by renatojobal** [comment]
Oh ya veo. Muchas gracias por responder @JamesJose7. 
Me queda una duda: ¿tu crees que podría usar este repositorio para convertilo en una github page? ¿O debería crear uno nuevo? Porque este github page también podría servir para que se referencie las políticas de privacidad en la aplicación de de IOS y también desde la plataforma web. Entonces mi pregunta es si estaría bien que este sea el repositorio para presentar las políticas o debería ser uno nuevo

**Comment by JamesJose7** [comment]
Yo lo haría en este repositorio.

**Comment by renatojobal** [comment]
Entiendo. Muchas gracias por responder 🤗
